FROM python:3.11-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

ENV TRANSFORMERS_CACHE=/app/cache
ENV TORCH_HOME=/app/torch_home

COPY . /app

RUN uv sync --frozen

RUN uv run src/docling/download_weights.py

ENTRYPOINT ["uv", "run", "src/docling/convert.py"]
